### ISSUE TITLE
Error after starting melonbar

### ISSUE THREAD

**Issue by noot** [onodera-punpun/melonbar#2] opened 2019-01-14 17:05 UTC
After doing go get, I ran:
```
go build
./melonbar
```

I then got the error `2019/01/14 12:03:24 dial tcp :6600: connect: connection refused`

Any help is much appreciated :)

**Comment by zeroeightysix** [comment] 2019-01-14 17:11
I blame https://github.com/onodera-punpun/melonbar/blob/9d5cf20d2826a213e9169f59f0d2666ca2952049/blocks.go#L68
If you've got mpd on your system, start it. If not, try removing the music block.

**Comment by noot** [comment] 2019-01-14 18:49
I installed mpd and it got rid of the error.  Getting `no such file or directory` now but this looks to be solved by issue #1 . thanks!

**Comment by CamilleScholtz** [comment] 2019-01-14 19:29
Closing this in favor of #3, which will hopefully produce a fix that will prevent issues caused by hard-coded things like this.

**Closed as completed by CamilleScholtz** 2019-01-14 19:29 UTC
